version: '3.8'

services:
  chat-service:
    build: ./server
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres